Get-AppxPackage -Name "MicrosoftTeams" -AllUsers | Remove-AppxPackage -AllUsers
Get-AppxPackage -Name "Microsoft.OneDriveSync" -AllUsers | Remove-AppxPackage -AllUsers 
Get-AppxPackage -Name "MicrosoftWindows.Client.WebExperience" -AllUsers | Remove-AppxPackage -AllUsers 
Get-AppxPackage -Name "Microsoft.549981C3F5F10" -AllUsers | Remove-AppxPackage -AllUsers 
Get-AppxPackage -Name "Microsoft.BingNews" -AllUsers | Remove-AppxPackage -AllUsers 
Get-AppxPackage -Name "Microsoft.BingWeather" -AllUsers | Remove-AppxPackage -AllUsers 
Get-AppxPackage -Name "Microsoft.GamingApp" -AllUsers | Remove-AppxPackage -AllUsers 
Get-AppxPackage -Name "Microsoft.GetHelp" -AllUsers | Remove-AppxPackage -AllUsers 
Get-AppxPackage -Name "Microsoft.GetStarted" -AllUsers | Remove-AppxPackage -AllUsers 
Get-AppxPackage -Name "Microsoft.Microsoft3DViewer" -AllUsers | Remove-AppxPackage -AllUsers 
Get-AppxPackage -Name "Microsoft.OfficeHub" -AllUsers | Remove-AppxPackage -AllUsers 
Get-AppxPackage -Name "Microsoft.People" -AllUsers | Remove-AppxPackage -AllUsers 
Get-AppxPackage -Name "Microsoft.MicrosoftSolitaireCollection" -AllUsers | Remove-AppxPackage -AllUsers 
Get-AppxPackage -Name "Microsoft.ToDos" -AllUsers | Remove-AppxPackage -AllUsers 
Get-AppxPackage -Name "Microsoft.WindowsAlarms" -AllUsers | Remove-AppxPackage -AllUsers 
Get-AppxPackage -Name "Microsoft.WindowsFeedbackHub" -AllUsers | Remove-AppxPackage -AllUsers 
Get-AppxPackage -Name "Microsoft.WindowsMaps" -AllUsers | Remove-AppxPackage -AllUsers 
Get-AppxPackage -Name "Microsoft.XboxGameCallableUI" -AllUsers | Remove-AppxPackage -AllUsers 
Get-AppxPackage -Name "Microsoft.XboxGameOverlay" -AllUsers | Remove-AppxPackage -AllUsers 
Get-AppxPackage -Name "Microsoft.XboxGamingOverlay" -AllUsers | Remove-AppxPackage -AllUsers 
Get-AppxPackage -Name "Microsoft.XboxIdentityProvider" -AllUsers | Remove-AppxPackage -AllUsers 
Get-AppxPackage -Name "Microsoft.XboxSpeechToTextOverlay" -AllUsers | Remove-AppxPackage -AllUsers 
Get-AppxPackage -Name "Microsoft.YourPhone" -AllUsers | Remove-AppxPackage -AllUsers 
Get-AppxPackage -Name "microsoft.windowscommunicationsapps" -AllUsers | Remove-AppxPackage -AllUsers
Get-AppxPackage -Name "Microsoft.PowerAutomateDesktop" -AllUsers | Remove-AppxPackage -AllUsers
Get-AppxPackage -Name "Microsoft.WindowsStore" -AllUsers | Remove-AppxPackage -AllUsers